region = "eu-central-1"
availabilityZone = "eu-central-1a"
prefix = "berlin"
media_instance_type = "t2.small"
database_instance_type = "t2.small"
key_name = "tungsten"
mediaami = "ami-034fffcc6a0063961"
